# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
sudo: false
language: go

notifications:
  email: change

os:
  - linux
  - osx

# "1.9" go-sciter is incompatible with 1.9
# The latest 1.9 version was 9646a0a383.

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"


branches:
  only:
    - master
    - travis

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - libgtk-3-dev
    - libgtk-3-0
    - libstdc++-6-pic

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_cache:
  - rm -rf $GOPATH/src/github.com/fynxiu/go-sciter/*
  - rm -rf $GOPATH/pkg/**/github.com/fynxiu/go-sciter

install:
  - export SDK_PATH=https://raw.githubusercontent.com/c-smile/sciter-sdk/master
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -so "$TRAVIS_BUILD_DIR/libsciter-gtk.so" $SDK_PATH/bin.lnx/x64/libsciter-gtk.so; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then curl -so "$TRAVIS_BUILD_DIR/libsciter.dylib" $SDK_PATH/bin.osx/libsciter.dylib; fi

# - go get golang.org/x/lint/golint

  - go get -u github.com/GeertJohan/go.rice
  - go get -u github.com/GeertJohan/go.rice/rice

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp "$TRAVIS_BUILD_DIR/libsciter.dylib" "$TRAVIS_BUILD_DIR/liblibsciter.dylib"; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi

  - export PATH="$PATH:$TRAVIS_BUILD_DIR"
  - export LIBRARY_PATH="$LIBRARY_PATH:$TRAVIS_BUILD_DIR"

  - gcc --version
  - go version
  - go env
  - echo $PWD


script:
  - go build

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd examples; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then go build ./...; fi
